spring.application.name=InfyDUGuesstimate
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/business_estimate?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=ALEX9597493670#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jackson.serialization.write-dates-as-timestamps=false
